-- Phase 12: Add thumbnail_url column to videos table for static JPEG thumbnails
-- Generated by pipeline FFmpeg -vframes 1 at 0.5s; used by VideoGrid <img> on iOS PWA
ALTER TABLE videos ADD COLUMN IF NOT EXISTS thumbnail_url text;
